[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "OpenOA"
dynamic = ["version"]
authors = [{name = "NREL PRUF OA Team", email = "openoa@nrel.gov"}]
readme = {file = "README.md", content-type = "text/markdown"}
description = "A package for collecting and assigning wind turbine metrics"
requires-python = ">=3.10,<3.14"
license = {file = "LICENSE.txt"}
dependencies = [
    "scikit-learn>=1.0,<1.7",
    "requests>=2.21.0",
    "eia-python>=1.22",
    "pyproj>=3.5",
    "shapely>=1.8",
    "numpy>=1.24",
    "pandas>=2.2,<3",
    "pygam>=0.11.0",
    "scipy>=1.7",
    "statsmodels>=0.11; python_version<'3.11'",
    "statsmodels>=0.13.3; python_version>='3.11'",
    "tqdm>=4.28.1",
    "matplotlib>=3.6",
    "bokeh>=3.3",
    "attrs>=22.2",
    "pytz",
    "pyyaml",
    "tabulate",
    "ipython",
    "ipywidgets",
]
keywords = [
    "python3",
    "wind-energy",
    "operations",
    "operational-analysis",
    "operational-assessement",
    "turbine-performance",
    "wind-plant-performance",
]
classifiers = [  # https://pypi.org/classifiers/
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Other Audience",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

[project.urls]
source = "https://github.com/NREL/OpenOA"
documentation = "https://openoa.readthedocs.io/"
issues = "https://github.com/NREL/OpenOA/issues"
changelog = "https://github.com/NREL/OpenOA/blob/main/CHANGELOG.md"

[project.optional-dependencies]
develop = [
  "pre-commit",
  "ruff",
  "isort",
  "pytest>=9",
  "pytest-cov>=2.8.1",
]
docs = [
  "Sphinx>=5.0,!=7.2.0",
  "pydata-sphinx-theme",
  "sphinx_design>=0.3",
  "sphinxcontrib-bibtex",
  "myst-nb",
  "myst-parser",
]
nrel-wind = ["h5pyd"]
reanalysis = [
  "cdsapi",
  "xarray[parallel]",
  "h5py",  # Required for netcdf4
  "netcdf4",
]
examples = [
  "openoa[reanalysis,nrel-wind]",
  "jupyterlab"
]
all = ["openoa[develop,docs,examples]"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["openoa", "test", "examples"]

[tool.setuptools.dynamic]
version = {attr = "openoa.__version__"}

[tool.coverage.report]
exclude_lines = [
  "# pragma: no cover",
  "def .+plot",
  "def plot_.+",
]

[tool.coverage.run]
# Coverage.py configuration file
# https://coverage.readthedocs.io/en/latest/config.html
branch = true
source = ["openoa/*"]
omit = [
  "setup.py",
  "tests/*"
]

[tool.pytest.ini_options]
python_files = [
  "test/*.py",
]
testpaths = [
  "test/unit/*.py",
  "test/regression/*.py",
]
cache_dir = ".cache"
filterwarnings = [
  "ignore::DeprecationWarning:sklearn.*:",
  "ignore::DeprecationWarning:patsy.*:",
  "ignore::DeprecationWarning:pygam.*:",
]

[tool.isort]
# https://github.com/PyCQA/isort
py_version = 310
src_paths = ["isort", "test"]
combine_as_imports = true
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
length_sort = true
length_sort_straight = true
lines_after_imports = 2
line_length = 100
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = "openoa"
known_third_party = [
    "numpy",
    "scipy",
    "pandas",
    "pygam",
    "tqdm",
    "statsmodels",
    "scikit_learn",
    "EIA-python",
    "requests",
    "pyproj",
    "shapely"
]


[tool.ruff]
src = ["openoa", "test"]
line-length = 100
target-version = "py310"
fix = true

[tool.ruff.lint]
select = [
  "F",
  "E",
  "W",
  "C4",
  "D",
  "UP",
  "NPY",
  "PTH",
  "RUF",
  "FBT",
  "B",
  "PIE",
  "T20",
  "SIM",
]

# D205: not using summary lines and descriptions, just descriptions
# D401: don't believe enough in imperative mode to make all the changes currently
# E501: > 550 line length errors from comments and docs, only use to fix lines, then turn off
# NPY002: Need to adopt NumPy >= 2 first
ignore = ["D205", "D401", "NPY002", "E501"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["F", "E", "W", "C4", "D", "UP", "NPY", "PTH", "RUF", "FBT", "B", "PIE", "T20", "SIM", ]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "sphinx/examples/*.ipynb",
    "examples/*.ipynb"
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
"*/__init__.py" = ["E501", "D104", "F401", "D415"]
"test/*" = ["D100", "D101", "D102", "D103"]
"examples/*.ipynb" = ["T201"]

[tool.ruff.lint.pydocstyle]
convention = "google"
